username = 'user_apoyo1'
password = 'Fortinate2017'
dsn = '10.10.10.6/p65dbprd'
port = 1512
encoding = 'UTF-8'

sql = """ insert into CASOS_BONOS(
            TICKET,
            DNI,
            CELULAR,
            CORREO,
            CASO,
            NOMBRE_BONO,
            FECHA_REGISTRO,
            DEPARTAMENTO,
            ID_CASOS,
            "APELLIDO PATERNO",
            "APELLIDO MATERNO",
            NOMBRES,
            BENEFICIARIO,
            PROVINCIA,
            DISTRITO,
            LUGAR,
            UBIGEO,
            BANCO,
            "DNI CONTACTO",
            "APELLIDO PATERNO CONTACTO",
            "APELLIDO MATERNO CONTACTO",
            "NOMBRES CONTACTO",
            "CELULAR CONTACTO",
            "CORREO CONTACTO",
            CONSULTA,
            REGISTRADOR,
            ESTADO,
            "TIPO DE ATENCION",
            EVALUADOR,
            "FECHA DE EVALUACION",
            "RESOLUCION DEL CASO",
            CONCLUSIONES,
            "TIPO BONO"
        )
        values(
            :02,
            :03,
            :04,
            :05,
            :06,
            :07,
            :08,
            :09,
            :10,
            :11,
            :12,
            :13,
            :14,
            :15,
            :16,
            :17,
            :18,
            :19,
            :20,
            :21,
            :22,
            :23,
            :24,
            :25,
            :26,
            :27,
            :28,
            :29,
            :30,
            :31,
            :32,
            :33,
            :34
        ) """
sql_completo = """ insert into CASOS_BONOS(
            TICKET,
            DNI,
            CELULAR,
            CORREO,
            CASO,
            NOMBRE_BONO,
            FECHA_REGISTRO,
            DEPARTAMENTO,
            ID_CASOS,
            "APELLIDO PATERNO",
            "APELLIDO MATERNO",
            NOMBRES,
            BENEFICIARIO,
            PROVINCIA,
            DISTRITO,
            LUGAR,
            UBIGEO,
            BANCO,
            "DNI CONTACTO",
            "APELLIDO PATERNO CONTACTO",
            "APELLIDO MATERNO CONTACTO",
            "NOMBRES CONTACTO",
            "CELULAR CONTACTO",
            "CORREO CONTACTO",
            "DEPARTAMENTO PERCEPTOR",
            "PROVINCIA PERCEPTOR",
            "DISTRITO PERCEPTOR",
            "UBIGEO PERCEPTOR",
            CONSULTA,
            REGISTRADOR,
            ESTADO,
            "TIPO DE ATENCION",
            EVALUADOR,
            "FECHA DE EVALUACION",
            "RESOLUCION DEL CASO",
            CONCLUSIONES,
            "TIPO BONO",
            "CODIGO ENTIDAD"
        )
        values(
            :02,
            :03,
            :04,
            :05,
            :06,
            :07,
            :08,
            :09,
            :10,
            :11,
            :12,
            :13,
            :14,
            :15,
            :16,
            :17,
            :18,
            :19,
            :20,
            :21,
            :22,
            :23,
            :24,
            :25,
            :26,
            :27,
            :28,
            :29,
            :30,
            :31,
            :32,
            :33,
            :34,
            :35,
            :36,
            :37,
            :38,
            :39
        ) """
